---
title: "COMPSIX_415.2 Homework 8"
author: "Emerson Sosa"
date: "3/24/2019"
output: 
   html_document:
     theme: darkly
     highlight: espresso
     code_folding: hide
     toc: true
     collapsed: true
     number_sections: true
     toc_depth: 1
---

```{r load_packages, warning=FALSE, message=FALSE}
library(ggplot2)
library(tidyverse)
library(dplyr)

library('rvest')
library(jsonlite)
library(leaflet)
library(htmltools)
```

```{r message=FALSE}

library(jsonlite)

##Dublin
dublin.url <- paste0("https://api.jcdecaux.com/vls/v1/stations?contract=",'Dublin',"&apiKey=f29cd91a8d938fff0f834c155c7c22f340a3fbf4")
dublin.api <- fromJSON(dublin.url, flatten = TRUE)


Dublin <- dublin.api %>% 
  mutate(longitude = position.lng, latitude = position.lat)


##Luxembourg
lux.url <- paste0("https://api.jcdecaux.com/vls/v1/stations?contract=",'Luxembourg',"&apiKey=f29cd91a8d938fff0f834c155c7c22f340a3fbf4")
lux.api <- fromJSON(lux.url, flatten = TRUE)


Luxembourg <- lux.api %>% 
  mutate(longitude = position.lng, latitude = position.lat)

##Seville
sev.url <- paste0("https://api.jcdecaux.com/vls/v1/stations?contract=",'Seville',"&apiKey=f29cd91a8d938fff0f834c155c7c22f340a3fbf4")
sev.api <- fromJSON(sev.url, flatten = TRUE)


Seville <- sev.api %>% 
  mutate(longitude = position.lng, latitude = position.lat)

##Stockholm seems to be down
##stockholm.url <- paste0("https://api.jcdecaux.com/vls/v1/stations?contract=",'Stockholm',"&apiKey=f29cd91a8d938fff0f834c155c7c22f340a3fbf4")
##stockholm.api <- fromJSON(stockholm.url, flatten = TRUE)


##stockholm.data <- stockholm.api %>% 
  #mutate(longitude = position.lng, latitude = position.lat)

##Ljubljana
ljub.url <- paste0("https://api.jcdecaux.com/vls/v1/stations?contract=",'Ljubljana',"&apiKey=f29cd91a8d938fff0f834c155c7c22f340a3fbf4")
ljub.api <- fromJSON(ljub.url, flatten = TRUE)


Ljubljana <- ljub.api %>% 
  mutate(longitude = position.lng, latitude = position.lat)

##Brisbane
bris.url <- paste0("https://api.jcdecaux.com/vls/v1/stations?contract=",'Ljubljana',"&apiKey=f29cd91a8d938fff0f834c155c7c22f340a3fbf4")
bris.api <- fromJSON(bris.url, flatten = TRUE)


Brisbane <- bris.api %>% 
  mutate(longitude = position.lng, latitude = position.lat)


##Function
map_it <- function(city) {
  map <- leaflet(city) %>% 
    addTiles() %>% 
    addMarkers()
  return(map)
}

cities <- c('Luxembourg', 'Dublin', 'Brisbane', 'Seville', 'Stockholm', 'Ljubljana')

##Try with Dublin, Luxembourg, Brisbane, Seville, Ljubljana. Stockholm does not have data. Also, using vector cities does not work. 
map_it(Dublin)

```


